ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - name: 51.250.35.129.nip.io
      path: /
      tls: true
      tlsSecret: 51.250.35.129.nip.io