apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    tier: paymentservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: paymentservice
      tier: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
        tier: paymentservice
    spec:
      containers:
      - name: server
        image: kitit/hipstershop:v.0.0.2
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "paymentservice"
        - name: CURRENCY_SERVICE_ADDR
          value: "app"
        - name: CART_SERVICE_ADDR
          value: "app"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "app"
        - name: CHECKOUT_SERVICE_ADDR
          value: "app"
        - name: SHIPPING_SERVICE_ADDR
          value: "app"
        - name: AD_SERVICE_ADDR
          value: "app"